name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests with coverage
      run: swift test --skip .integration --enable-code-coverage
    
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export \
          -format="lcov" \
          -instr-profile=.build/debug/codecov/default.profdata \
          -ignore-filename-regex=".build|Tests" \
          .build/debug/xcsentinelPackageTests.xctest/Contents/MacOS/xcsentinelPackageTests > coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.lcov
        flags: unittests
        name: xcsentinel
        swift_project: xcsentinel
        fail_ci_if_error: false
        verbose: true
    
    - name: Build for release
      run: swift build -c release -v